---
#- name: create cron job for backup
#  cron: name="backup" minute="0" hour="0" job="php {{site_dir}}/app/console dizda:backup:start"

- name: Copy parameters.yml
  sudo: yes
  sudo_user: "{{project_user}}"
  template: >-
    src=templates/parameters.yml
    dest={{site_dir}}/app/config/parameters.yml

- name: Run composer install.
  sudo: yes
  sudo_user: "{{project_user}}"
  shell: 'cd {{site_dir}} && php {{site_dir}}/composer.phar install --no-interaction'

- name: sf warm up cache
  sudo: yes
  sudo_user: "{{project_user}}"
  shell: 'php {{site_dir}}/app/console cache:clear --env=prod --no-debug'

- name: sf update DB schema
  sudo: yes
  sudo_user: "{{project_user}}"
  shell: 'php {{site_dir}}/app/console doctrine:schema:update --force --env=prod --no-debug'

- name: sf install web assets
  shell: 'php app/console assets:install'
  args:
      chdir: '{{site_dir}}'
  sudo: yes
  sudo_user: "{{project_user}}"

- name: sf generate assets
  shell: 'php {{site_dir}}/app/console assetic:dump'
  sudo: yes
  sudo_user: "{{project_user}}"
