services:
    cmf_create.persistence.orm.object_mapper:
        class: Midgard\CreatePHP\Mapper\DoctrineOrmMapper
        arguments:
            - "%cmf_create.map%"
            - "@doctrine"
    cmf_seo.extractor_strategy.extra:
        class: Symfony\Cmf\Bundle\SeoBundle\Extractor\ExtrasExtractor
        tags:
            -  { name: cmf_seo.extractor }